### ISSUE TITLE
Question about trained model

### ISSUE THREAD

**Issue by chmxu** [Gaoyiminggithub/Graphonomy#14]
Thanks for sharing this repo.
I have downloaded the checkpoint 'inference.pth' in the Model section in README.
And when i load the model weight i find that the 'target_featuremap_2_graph.pre_fea' and 'target_featuremap_2_graph.weight', which are contained in the feature to graph projection module, are all 0, which i think is not so reasonable. 
Am i having any misunderstanding or maybe I have downloaded a wrong model?

**Comment by Gaoyiminggithub** [comment]
Thanks for your attention.
I have checked the model in README.md in which some modules are 0. The reason is that when I re-trained our models based on the code in Github, I commented the `reset_parameters()` function.
Without the double-check for the model, we are very sorry for the inconvenience. And I start training with the correct version of the code.
Thanks for your kindly help.

**Comment by chmxu** [comment]
Thanks. Hope to see the update version soon.

**Comment by Gaoyiminggithub** [comment]
Hi @loadder 
Thanks for your attention.
The correct pretrained model of CIHP is in [here](https://drive.google.com/file/d/1eUe18HoH05p0yFUd_sN6GXdTj82aW0m9/view?usp=sharing), and the model of PASCAL is in [here](https://drive.google.com/file/d/1E_V_gVDWfAJFPfe-LLu2RQaYQMdhjv9h/view?usp=sharing).
We are so sorry for the inconvenience.

**Comment by yarin05** [comment]
@Gaoyiminggithub 
Thank you for keeping support and maintenance the project.
Should I expect changes also in the 'Universal' model?

**Comment by chmxu** [comment]
Thanks!
